apiVersion: apps/v1

kind: Deployment

metadata:
  name: skywatch-worker

  labels:
    app: skywatch-worker


spec:

  replicas: {{ .Values.worker.replicas }}

  selector:

    matchLabels:
      app: skywatch-worker


  template:

    metadata:

      labels:
        app: skywatch-worker


    spec:

      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}

      containers:

        - name: worker

          image: "{{ .Values.worker.image.repository }}:{{ .Values.worker.image.tag }}"

          env:

            - name: RABBITMQ_HOST
              value: skywatch-rabbitmq

            - name: RABBITMQ_PORT
              value: "5672"

            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: skywatch-rabbitmq
                  key: RABBITMQ_DEFAULT_USER

            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: skywatch-rabbitmq
                  key: RABBITMQ_DEFAULT_PASS